name: Build and copy frontend to the backend repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Timestamp
        run: echo "Timestamp:$(date)" > ./timestamp.txt

      - name: Commit changes to the repository
        run: |
          git config user.email "tbermanseder@gmail.com"
          git config user.name "agilethief"

          # Display configured user
          git config user.email
          git config user.name

          git add .
          git commit -m "Update frontend build [skip ci]"

          # Display remote URLs
          git remote -v

      - name: Push to the repository
        run: git push https://agilethief:${{ secrets.GH_BLOG_TOKEN }}@github.com/agilethief/TBWebappBlog.git HEAD:main
