name: Build and copy frontend to the backend repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Get list of folders
        run: dir

      - name: Navigate to frontend directory
        run: cd frontend

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Copy frontend build to backend repository
        working-directory: .
        run: |
          mkdir ../backend-repo/frontend
          cp -r * ../backend-repo/frontend/
