name: Build and copy frontend to the backend repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Navigate to frontend directory
        run: cd frontend

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Copy frontend build to backend repository
        run: |
          cp -r ./frontend/dist ./backend/tbwebappbackend/react_build

      - name: Commit changes to the repository
        run: |
          git config --global user.email "tbermanseder@gmail.com"
          git config --global user.name "agilethief"
          git add .
          git commit -m "Update frontend build [skip ci]"
          git push https://${{ secrets.GH_BLOG_TOKEN }}@github.com/Agilethief/TBWebappBlog.git HEAD:main
